INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, BIRTH_DATE, WANTS_NEWS_LETTER) VALUES ('Edu', 'Martorell', '2003-12-08', false);
INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, BIRTH_DATE, WANTS_NEWS_LETTER) VALUES ('Victor', 'Gonzalez', '2001-03-12', false);


INSERT INTO COURSE (TITLE) VALUES ('M01');
INSERT INTO COURSE (TITLE) VALUES ('M02');
INSERT INTO COURSE (TITLE) VALUES ('M03');
INSERT INTO COURSE (TITLE) VALUES ('M04');
INSERT INTO COURSE (TITLE) VALUES ('M05');
INSERT INTO COURSE (TITLE) VALUES ('M06');
INSERT INTO COURSE (TITLE) VALUES ('M07');
INSERT INTO COURSE (TITLE) VALUES ('M08');
INSERT INTO COURSE (TITLE) VALUES ('M09');
INSERT INTO COURSE (TITLE) VALUES ('M10');
INSERT INTO COURSE (TITLE) VALUES ('M11');


INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('M01/Materials/UF1', 1);
INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('M01/Materials/UF2', 1);
INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('M01/Materials/UF3', 1);
INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('M02/Materials', 2);
INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('M03/Materials', 3);
INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('M04/Materials', 4);
INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('M05/Materials', 5);
INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('M06/Materials', 6);
INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('M07/Materials', 7);
INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('M08/Materials', 8);


INSERT INTO JOINED_COURSES (STUDENT_ID, COURSE_ID) VALUES (1,7)
INSERT INTO JOINED_COURSES (STUDENT_ID, COURSE_ID) VALUES (1,8)
INSERT INTO JOINED_COURSES (STUDENT_ID, COURSE_ID) VALUES (2,1)
INSERT INTO JOINED_COURSES (STUDENT_ID, COURSE_ID) VALUES (2,2)